### ISSUE TITLE
Fatal System.NullReferenceException

### ISSUE THREAD

**Issue by BrettyJones** [AngleSharp/AngleSharp#1036]
Hi, an issue is causing a fatal error in my program when using AngleSharp.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AngleSharp
  StackTrace:
   at AngleSharp.Html.Parser.HtmlDomBuilder.<ParseAsync>d__25.MoveNext() in /_/src/AngleSharp/Html/Parser/HtmlDomBuilder.cs:line 115
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Html.Parser.HtmlParser.<ParseAsync>d__33.MoveNext() in /_/src/AngleSharp/Html/Parser/HtmlParser.cs:line 256
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Html.Parser.HtmlParser.<AngleSharp-Html-Parser-IHtmlParser-ParseDocumentAsync>d__27.MoveNext() in /_/src/AngleSharp/Html/Parser/HtmlParser.cs:line 205
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Browser.DefaultNavigationHandler.<NavigateAsync>d__2.MoveNext() in /_/src/AngleSharp/Browser/DefaultNavigationHandler.cs:line 35
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Dom.Document.<LocationChanged>d__399.MoveNext() in /_/src/AngleSharp/Dom/Internal/Document.cs:line 1493
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 980
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 928
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1252
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 820

  This exception was originally thrown at this call stack:
    AngleSharp.Html.Parser.HtmlDomBuilder.ParseAsync(AngleSharp.Html.Parser.HtmlParserOptions, System.Threading.CancellationToken) in HtmlDomBuilder.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    AngleSharp.Html.Parser.HtmlParser.ParseAsync(AngleSharp.Html.Dom.HtmlDocument, System.Threading.CancellationToken, string) in HtmlParser.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    AngleSharp.Html.Parser.HtmlParser.AngleSharp.Html.Parser.IHtmlParser.ParseDocumentAsync(AngleSharp.Dom.IDocument, System.Threading.CancellationToken) in HtmlParser.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    AngleSharp.Browser.DefaultNavigationHandler.NavigateAsync(AngleSharp.Io.DocumentRequest, System.Threading.CancellationToken) in DefaultNavigationHandler.cs
    ...
    [Call Stack Truncated]

**Comment by FlorianRappl** [comment]
Sorry more information needed.

**Comment by BrettyJones** [comment]
I am attempting to reproduce the error and I will revert shortly.  In the meantime, a further fatal error occurred...

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AngleSharp
  StackTrace:
   at AngleSharp.Text.TextSource.AppendContentFromBuffer(Int32 size) in /_/src/AngleSharp/Text/TextSource.cs:line 380
   at AngleSharp.Text.TextSource.<ReadIntoBufferAsync>d__35.MoveNext() in /_/src/AngleSharp/Text/TextSource.cs:line 348
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at AngleSharp.Text.TextSource.<ExpandBufferAsync>d__34.MoveNext() in /_/src/AngleSharp/Text/TextSource.cs:line 339
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at AngleSharp.Html.Parser.HtmlDomBuilder.<ParseAsync>d__25.MoveNext() in /_/src/AngleSharp/Html/Parser/HtmlDomBuilder.cs:line 120
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Html.Parser.HtmlParser.<ParseAsync>d__33.MoveNext() in /_/src/AngleSharp/Html/Parser/HtmlParser.cs:line 256
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Html.Parser.HtmlParser.<AngleSharp-Html-Parser-IHtmlParser-ParseDocumentAsync>d__27.MoveNext() in /_/src/AngleSharp/Html/Parser/HtmlParser.cs:line 205
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Browser.DefaultNavigationHandler.<NavigateAsync>d__2.MoveNext() in /_/src/AngleSharp/Browser/DefaultNavigationHandler.cs:line 35
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at AngleSharp.Dom.Document.<LocationChanged>d__399.MoveNext() in /_/src/AngleSharp/Dom/Internal/Document.cs:line 1493
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 980
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 928
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1252
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 820

  This exception was originally thrown at this call stack:
    AngleSharp.Text.TextSource.AppendContentFromBuffer(int) in TextSource.cs
    AngleSharp.Text.TextSource.ReadIntoBufferAsync(System.Threading.CancellationToken) in TextSource.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    AngleSharp.Text.TextSource.ExpandBufferAsync(long, System.Threading.CancellationToken) in TextSource.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    AngleSharp.Html.Parser.HtmlDomBuilder.ParseAsync(AngleSharp.Html.Parser.HtmlParserOptions, System.Threading.CancellationToken) in HtmlDomBuilder.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    AngleSharp.Html.Parser.HtmlParser.ParseAsync(AngleSharp.Html.Dom.HtmlDocument, System.Threading.CancellationToken, string) in HtmlParser.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
    ...
    [Call Stack Truncated]

**Comment by FlorianRappl** [comment]
Sorry this is an indicator that something is awfully wrong with your system. I think there might be a memory leak or even corruption somewhere.

Closing as long as their is no reproducible.
