### ISSUE TITLE
Assembly load exception

### ISSUE THREAD

**Issue by asgerhallas** [AngleSharp/AngleSharp#1042]
# Bug Report

When I run the example code from the readme, in a NET5.0 console application, I get the following exception: 

System.IO.FileLoadException
Could not load file or assembly 'System.Net.Security, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Invalid assembly public key. (0x8013141E)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at AngleSharp.Io.DefaultHttpRequester.RequestState.RequestAsync(CancellationToken cancellationToken)
   at AngleSharp.Io.DefaultHttpRequester.PerformRequestAsync(Request request, CancellationToken cancellationToken)
   at AngleSharp.Io.BaseRequester.RequestAsync(Request request, CancellationToken cancel)
   at AngleSharp.Io.BaseLoader.LoadAsync(Request request, CancellationToken cancel)
   at AngleSharp.Browser.DefaultNavigationHandler.NavigateAsync(DocumentRequest request, CancellationToken cancel)

Running AngleSharp 0.16.1. 

Do you have any good ideas about what that is? :)

**Comment by asgerhallas** [comment]
Ok, an upgrade of VS did the trick. Sorry to disturb :)
