### ISSUE TITLE
NullReferenceException at HtmlDomBuilder

### ISSUE THREAD

**Issue by alexanderkozlenko** [AngleSharp/AngleSharp#114]
master, ver 751162584e4780d33d3f8ecd869bb37bf5f905a5

```
at AngleSharp.Parser.Html.HtmlDomBuilder.Consume(HtmlToken token)
at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(HtmlParserOptions options)
at AngleSharp.Parser.Html.HtmlParser.Parse(String source)
```

```
<!DOCTYPE html><body><!---------------------GA--------------------------- --></body></html>
```

**Comment by FlorianRappl** [comment]
Thanks for the report. I'll look into that!

**Comment by FlorianRappl** [comment]
I will release v0.8.8 tomorrow. The fix will be included. Thanks again for spotting the issue.

**Comment by alexanderkozlenko** [comment]
Thanks for quick solution!
