### ISSUE TITLE
Unable to route https requests via a proxy

### ISSUE THREAD

**Issue by stuxamber** [AngleSharp/AngleSharp#1143]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

Hello, before I have created this issue, I have searched high and low on both github/stackoverflow and none of the suggested solutions worked.

I am trying to get my https requests through via a proxy and it seems like its failing on every level possible. Using AngleSharp shouldn't be this difficult.

I have also simplified the testing by using Fiddler classic as a proxy, and the results are the same. WebClient goes through, and AngleSharp failed. It also shows that the handshake was successful, indicating no errors with the certificates whatsoever. 

Also, I discovered that AngleSharp is not passing the "User-Agent" to the requests.
`handler.Properties.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61");` doesn't do anything.

If the request went through successfully, the raw request is

> GET https://stackoverflow.com/ HTTP/1.1
> Host: stackoverflow.com
> Accept: text/html,application/xhtml+xml,application/xml
> Referer: 
> Cookie: 

And the response raw would be:

> HTTP/1.1 403 Forbidden
> Date: Sun, 22 Oct 2023 13:02:29 GMT
> Content-Type: text/html; charset=UTF-8
> Content-Length: 5565
> Connection: keep-alive
> X-Frame-Options: SAMEORIGIN
> Referrer-Policy: same-origin
> Cache-Control: max-age=15
> Expires: Sun, 22 Oct 2023 13:02:44 GMT
> Set-Cookie: __cf_bm=CqGg2k6sTAMDuUagzR3trDaQyZzp_WT6rHKTbddQRfQ-1697979749-0-AUMtdxDS0ZxPOWn0micSJpVd0xAfo/yjwd0JiTDqScpNg5u/nmk21I5RGUtr/GQU3K/TXJ8XHijMK7hyR2WWU+E=; path=/; expires=Sun, 22-Oct-23 13:32:29 GMT; domain=.stackoverflow.com; HttpOnly; Secure
> X-DNS-Prefetch-Control: off
> Server: cloudflare
> CF-RAY: 81a1ef58fe724028-SIN
> 
> <html>
> <head>
>     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
>     <title>Forbidden - Stack Exchange</title>
>     <style type="text/css">body{background:#fff url(data:text/html;charset=utf-8;base64,PGh0bWw+CjxoZWFkPgogICAgPG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9VVRGLTgiIC8+CiAgICA8dGl0bGU+Rm9yYmlkZGVuIC0gU3RhY2sgRXhjaGFuZ2U8L3RpdGxlPgogICAgPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCQlib2R5CgkJewoJCQljb2xvcjogIzMzMzsKCQkJZm9udC1mYW1pbHk6ICdIZWx2ZXRpY2EgTmV1ZScsIEFyaWFsLCBzYW5zLXNlcmlmOwoJCQlmb250LXNpemU6IDE0cHg7CgkJCWJhY2tncm91bmQ6ICNmZmYgdXJsKCdpbWcvYmctbm9pc2UucG5nJykgcmVwZWF0IGxlZnQgdG9wOwoJCQlsaW5lLWhlaWdodDogMS40OwoJCX0KCQloMQoJCXsKCQkJZm9udC1zaXplOiAxNzAlOwoJCQlsaW5lLWhlaWdodDogMzRweDsKCQkJZm9udC13ZWlnaHQ6IG5vcm1hbDsKCQl9CgkJYSB7IGNvbG9yOiAjMzY2ZmIzOyB9CgkJYTp2aXNpdGVkIHsgY29sb3I6ICMxMjQ1N2M7IH0KCQkud3JhcHBlciB7CgkJCXdpZHRoOjk2MHB4OwoJCQltYXJnaW46IDEwMHB4IGF1dG87CgkJCXRleHQtYWxpZ246bGVmdDsKCQl9CgkJLm1zZyB7CgkJCWZsb2F0OiBsZWZ0OwoJCQl3aWR0aDogNzAwcHg7CgkJCXBhZGRpbmctdG9wOiAxOHB4OwoJCQltYXJnaW4tbGVmdDogMThweDsKCQl9CiAgICA8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5PgogICAgPGRpdiBjbGFzcz0id3JhcHBlciI+CgkJPGRpdiBzdHlsZT0iZmxvYXQ6IGxlZnQ7Ij4KCQkJPGltZyBzcmM9Imh0dHBzOi8vY2RuLnNzdGF0aWMubmV0L3N0YWNrZXhjaGFuZ2UvaW1nL2FwcGxlLXRvdWNoLWljb24ucG5nIiBhbHQ9IlN0YWNrIEV4Y2hhbmdlIiAvPgoJCTwvZGl2PgoJCTxkaXYgY2xhc3M9Im1zZyI+CgkJCTxoMT5BY2Nlc3MgRGVuaWVkPC9oMT4KICAgICAgICAgICAgICAgICAgICAgICAgPHA+VGhpcyBJUCBhZGRyZXNzIDo6Q0xJRU5UX0lQOjogaGFzIGJlZW4gYmxvY2tlZCBmcm9tIGFjY2VzcyB0byBvdXIgc2VydmljZXMuIElmIHlvdSBiZWxpZXZlIHRoaXMgdG8gYmUgaW4gZXJyb3IsIHBsZWFzZSBjb250YWN0IHVzIGF0IDxhIGhyZWY9Im1haWx0bzp0ZWFtQHN0YWNrZXhjaGFuZ2UuY29tP1N1YmplY3Q9QmxvY2tlZCUyMCJ9ICsgY2xpZW50LmlwICsgeyIlMjAoUmVxdWVzdCUyMElEJTNBJTIwIn0gKyByZXEueGlkICsgIi0iICsgc2VydmVyLmRhdGFjZW50ZXIgeyIpIj50ZWFtQHN0YWNrZXhjaGFuZ2UuY29tPC9hPi48L3A+CiAgICAgICAgICAgICAgICAgICAgICAgIDxwPldoZW4gY29udGFjdGluZyB1cywgcGxlYXNlIGluY2x1ZGUgdGhlIGZvbGxvd2luZyBpbmZvcm1hdGlvbiBpbiB0aGUgZW1haWw6PC9wPgogICAgICAgICAgICAgICAgICAgICAgICA8cD5NZXRob2Q6IGJsb2NrPC9wPgogICAgICAgICAgICAgICAgICAgICAgICA8cD5JUDogOjpDTElFTlRfSVA6OjwvcD4KICAgICAgICAgICAgICAgICAgICAgICAgPHA+UkFZIElEOiA6OlJBWV9JRDo6PC9wPgogICAgICAgICAgICAgICAgICAgICAgICA8cD5HRU86IDo6R0VPOjo8L3A+CgkJPC9kaXY+Cgk8L2Rpdj4KCTxzY3JpcHQ+ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2pzbG9jYXRpb24nKS5pbm5lckhUTUwgPSB3aW5kb3cubG9jYXRpb24uaHJlZjs8L3NjcmlwdD4KPC9ib2R5Pgo8L2h0bWw+) repeat 0 0;color:#333;font-family:Helvetica Neue,Arial,sans-serif;font-size:14px;line-height:1.4}h1{font-size:170%;font-weight:400;line-height:34px}a{color:#366fb3}a:visited{color:#12457c}.wrapper{margin:100px auto;text-align:left;width:960px}.msg{float:left;margin-left:18px;padding-top:18px;width:700px}</style>
> 
> </head>
> <body>
>     <div class="wrapper">
> 		<div style="float: left;">
> 			<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJ4AAACeCAMAAAD0W0NJAAABKVBMVEX///8AAACP2PZisN9isN9RhMEYUpcybrY6bKYYUpdRhMEybrZGotlRhMEYU5disN9GotkYU5c6bKaP2PYYU5cYU5eP2PaP2PaP2PaP2PaP2PaP2PY6bKYYU5eP2PY6bKYYUpcYUpeP2PYYUpeP2PaP2PYYUpc6bKYYU5c6bKY6bKYYUpcYU5c6bKaP2PYYUpcYU5eP2PY6bKY6bKYYUpcYUpcYUpc6bKZbrd46bKY3aqVJf75isN86bKYYUpchWZtisN8YU5dRp9sYUpdRhMFRhMEYUpc6dLkaVJhZrN1FfL1gr98lXJ1drd5RhMEeV5otYqA+dropX58ybrY4aqU6bKZGotk0b7dRp9s6dLkYU5dLgL9DerxIo9k0Z6OP2PZisN8YUpdYq93h0Z0aAAAASHRSTlMAAIBAgIC/QL9AQICAv7+/QBBAv8+fQDDvYJ/fMGAQ7+8wUM8gr2AQr5+AUDCPcIDvz89wEJ9w30Cvv4BgII9AMHCA32AwIEDHFgI6AAADCElEQVR4XuzAgQAAAADDoPtT32AEtQAAcPbq4ARiEArC8K4tCE+fggdJroF0sJ1M/13sOcf31IGAfwHDd5vvo0N6mJjK8dwf4aVSMb1c+hSeRCyq6jCvnVjYncZ4KWNt6uRxdID6eCQdoF5ey2AkTt4JSrW5eB2kgotXwao5eAJawcEroFUdvAxeycwTELvMvAvEipkXQCyaeQXEbjMvgtkc3uZt3uZpYGb/XGqv4W3e5v3+zM6xCYVQEABBQUNBy/mBkZmI6XLJg8/1X4SZlwmCwk4F03/uN18e96b/54KLsBeYe4G5F5h7gbkXmHuJuZeYe4m5l5h7ibmXmHuJubdh7h1N2audsVc7Y692xl7tjL3aGXu1E/f2xru9ZXjTOt573DvZsUMCAAAQiIEgUB/pLf0zUQCBQO4STI9LQN6KvK4X1skwO8cmEAJAFAUvOxAs6xA2ED4vENH+67hwUxXRNxXM6d4432LlkJd6wdwL5l4w94K5F8y9YO4Fc2/H3CvMvcLcK8y9wtwrzL3C3CvMvW1R9npn7PXO2Oudsdc7Y693z/V+w1nT97o/O3avgjAQBAFYm3B16kAuBBJMCIH4h4I2glgEIqKNhTDv/xLWInK3u8eaIvMEHwcHMztdCcLwJt7Ea4x39pE4ZJ55+OY+QBw6T0GnwRswZl6PMfN6jJnX40+8haYuIvMqik6ft1TUYU3mJYo6bOiVIHXobgiXjM5z/I0rwuXEaCyxmg4tp1AZLZ1dcXixkg4tr47udHQ5sy2XWw2dzbhlPkkFuufvfPAK3tb45XtRdG5eIZlCSfelu4R8PFvLllrZ8HTw0kVn8ZCMDUcHD11eB9m5h6oj6+DS5cfs3Y4d4iAMwGAU5kkMSUnrqJ+Y2A0I1+D+ByEkkxOQkPBEn6357N8fzvDb9d39/HF5rHvs539/CS6HumZPyWvMvMbMa8y8xswrzLzCzCvMvMLMK8y8wswrzLwFMy/DzMtAzMtAzMtAzMtAzMtAzMtAzNsCMW9bEfOWle94/qZpmqYXVsy/bDxskC4AAAAASUVORK5CYII=" alt="Stack Exchange" />
> 		</div>
> 		<div class="msg">
> 			<h1>Access Denied</h1>
>                         <p>This IP address x.x.x.x has been blocked from access to our services. If you believe this to be in error, please contact us at <a href="/cdn-cgi/l/email-protection#374352565a77444356545c524f545f565950521954585a086442555d5254430a755b58545c5253120507" } + client.ip + {"%20(Request%20ID%3A%20"} + req.xid + "-" + server.datacenter {")"><span class="__cf_email__" data-cfemail="9eeafbfff3deedeafffdf5fbe6fdf6fff0f9fbb0fdf1f3">[email&#160;protected]</span></a>.</p>
>                         <p>When contacting us, please include the following information in the email:</p>
>                         <p>Method: block</p>
>                         <p>IP: x.x.x.x</p>
>                         <p>RAY ID: 81a1ef58fe724028</p>
>                         <p>GEO: SG</p>
> 		</div>
> 	</div>
> 	<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.getElementById("jslocation").innerHTML=window.location.href;</script>
> </body>
> </html>

Due to a bad request, stackoverflow "blocks" the request, but if I am surfing stackoverflow on a browser, I can access it fine (no block on my IP).

On a basic level, I did the following (without a proxy):

```
var config = Configuration.Default.WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("https://api.ipify.org/");
Console.WriteLine(document.DocumentElement.OuterHtml);
```
This works fine.

On the next attempt, this will fail almost immediately.

It will throw a 

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=AngleSharp
>   StackTrace:
>    at AngleSharp.Text.TextSource.<DetectByteOrderMarkAsync>d__33.MoveNext()
>    at AngleSharp.Text.TextSource.<ExpandBufferAsync>d__34.MoveNext()
>    at AngleSharp.Html.Parser.HtmlDomBuilder.<ParseAsync>d__25.MoveNext()
>    at AngleSharp.Html.Parser.HtmlParser.<ParseAsync>d__33.MoveNext()
>    at AngleSharp.Html.Parser.HtmlParser.<AngleSharp-Html-Parser-IHtmlParser-ParseDocumentAsync>d__27.MoveNext()
>    at AngleSharp.Browser.DefaultNavigationHandler.<NavigateAsync>d__2.MoveNext()
>    at Testing.Program.<Main>d__0.MoveNext() in C:\Users\xxxxxx\source\repos\Testing\Testing\Program.cs:line 32
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
>     Testing.Program.Main(string[]) in Program.cs

```
var handler = new HttpClientHandler
{
    Proxy = new WebProxy(String.Format("{0}:{1}", "x.x.x.x", "1111"), false),
    Credentials = new NetworkCredential("yyyyyy", "zzzzz"),
    UseProxy = true,
    UseDefaultCredentials = false,
};

var config = Configuration.Default.WithRequesters(handler).WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("https://api.ipify.org/");
Console.WriteLine(document.Body.TextContent);

```

The following works fine when I used it with a WebClient.

```
var client = new WebClient();
client.Proxy = new WebProxy("x.x.x.x:1111");
client.Proxy.Credentials = new NetworkCredential("yyyyyy", "zzzzzz");
Console.WriteLine(client.DownloadString("https://api.ipify.org/"));
```

### Steps to Reproduce

As shown above.

### Expected Behavior

Expect the https request to go through when using AngularSharp

### Actual Behavior

Returning null reference.

### Possible Solution / Known Workarounds

What I am doing right now is, using WebClient to pull the data via proxy and passing the output back to AngularSharp.

**Comment by stuxamber** [comment]
Closing the issue as I don't see it working out in the long run. Too many conflicting variables in play, especially HttpClient that doesn't allow certain headers to be modified/added because it's not "in-line" with specifications.

I can provide the same headers that's used by WebClient and it will still fail with AngleSharp request.

I will stick to use WebClient with proxy to pull the data instead. Thanks.
