### ISSUE TITLE
InvalidOperationException: Stack empty in AngleSharp.Html.Parser.HtmlDomBuilder

### ISSUE THREAD

**Issue by mschessler** [AngleSharp/AngleSharp#1176]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.CloseTemplateMode()
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.CloseTemplate()
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.InHead(StructHtmlToken& token)
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.InBodyEndTag(StructHtmlToken& tag)
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.InBody(StructHtmlToken& token)
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.Home(StructHtmlToken& token)
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.Consume(StructHtmlToken& token)
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.Parse(HtmlParserOptions options, TokenizerMiddleware middleware)
   at AngleSharp.Html.Parser.HtmlParser.Parse(HtmlDocument document, String stopAt)
   at AngleSharp.Html.Parser.HtmlParser.ParseDocument(Char[] source, Int32 length)

### Steps to Reproduce

```
var html = "<svg><template><title><v></temPlate>";
var parser = new AngleSharp.Html.Parser.HtmlParser();
parser.ParseDocument(html.ToCharArray(), 0);
```

### Expected Behavior

Don't crash 

### Actual Behavior

Crash

**Comment by FlorianRappl** [comment]
Thanks! Fixed in latest preview.
