### ISSUE TITLE
NullReferenceException when using own HttpClient

### ISSUE THREAD

**Issue by pandene** [AngleSharp/AngleSharp#1181]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

When creating a BrowsingContext with an existing HTTPClient and an error occur with the connection, such as an invalid host that cause a socket exception, this will result in a null reference exception from angelsharp 

### Steps to Reproduce

```
var httpClient = new HttpClient();
httpClient.BaseAddress =new Uri("http://invalid");

var context = BrowsingContext.New(Configuration.Default
    .With(new HttpClientRequester(httpClient))  // When commenting this out, it works as expected
    .WithDefaultLoader());
 var document = await context.OpenAsync("http://invalid");
```

### Expected Behavior

The same should happen when not using your own HttpClient. That is a document is returned from the OpenAsunc call

### Actual Behavior

Stack trace
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AngleSharp.Text.WritableTextSource.DetectByteOrderMarkAsync(CancellationToken cancellationToken)
   at AngleSharp.Text.WritableTextSource.ExpandBufferAsync(Int64 size, CancellationToken cancellationToken)
   at AngleSharp.Html.Parser.HtmlDomBuilder`2.ParseAsync(HtmlParserOptions options, TokenizerMiddleware middleware, CancellationToken cancelToken)
   at AngleSharp.Html.Parser.HtmlParser.ParseAsync(HtmlDocument document, CancellationToken cancel, String stopAt)
   at AngleSharp.Html.Parser.HtmlParser.AngleSharp.Html.Parser.IHtmlParser.ParseDocumentAsync(IDocument document, CancellationToken cancel)
   at AngleSharp.Browser.DefaultNavigationHandler.NavigateAsync(DocumentRequest request, CancellationToken cancel)
   at Program.<Main>$(String[] args)
```

**Comment by FlorianRappl** [comment]
Can you elaborate in what project (and potentially for which companies) you are using AngleSharp?
