### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#159]
StackTrace:
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at AngleSharp.TextSource.get_Item(Int32 index)
   at AngleSharp.Parser.BaseTokenizer.NormalizeBackward(Char p)
   at AngleSharp.Parser.BaseTokenizer.BackUnsafe()
   at AngleSharp.Parser.BaseTokenizer.Back()
   at AngleSharp.Parser.Html.HtmlTokenizer.DataText(Char c)
   at AngleSharp.Parser.Html.HtmlTokenizer.Data(Char c)
   at AngleSharp.Parser.Html.HtmlTokenizer.Get()
   at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(HtmlParserOptions options)
   at AngleSharp.Parser.Html.HtmlParser.Parse(String source)

**Comment by FlorianRappl** [comment]
Source of the document where this happened? What version of AngleSharp did you use?

**Comment by useruser1** [comment]
Oh! I see that the issue has been resolved in .9.2

**Comment by FlorianRappl** [comment]
Alright - glad that was fixed already (#150)!

**Comment by useruser1** [comment]
Hmm, the problem is back
