### ISSUE TITLE
Invalid character detected.

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#160]
at AngleSharp.Dom.Element.SetAttribute(String name, String value)
   at AngleSharp.Parser.Html.HtmlForeignExtensions.AdjustAttribute(Element element, String name, String value)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InBodyStartTag(HtmlTagToken tag)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InBody(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Home(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Consume(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(HtmlParserOptions options)
   at AngleSharp.Parser.Html.HtmlParser.Parse(String source)

example source - http://mems.duke.edu/faculty

**Comment by FlorianRappl** [comment]
Thanks for the report. I was able to identify the problem (invalid character in foreign element attribute) and fix the behavior. The problem will be fixed in the upcoming release (v0.9.3).
