### ISSUE TITLE
The object can not be found here.

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#161]
at AngleSharp.Dom.Collections.NamedNodeMap.RemoveNamedItem(String name)
   at AngleSharp.Dom.Svg.SvgElement.<.ctor>b__0(String value)
   at AngleSharp.Dom.Collections.NamedNodeMap.CallHandlers(String name, String value)
   at AngleSharp.Dom.Collections.NamedNodeMap.RaiseChangedEvent(Attr attr, String newValue, String oldValue)
   at AngleSharp.Dom.Collections.NamedNodeMap.RemoveNamedItemOrDefault(String name)
   at AngleSharp.Dom.Collections.NamedNodeMap.RemoveNamedItem(String name)
   at AngleSharp.Dom.Svg.SvgElement.<.ctor>b__0(String value)
   at AngleSharp.Dom.Collections.NamedNodeMap.CallHandlers(String name, String value)
   at AngleSharp.Dom.Collections.NamedNodeMap.RaiseChangedEvent(Attr attr, String newValue, String oldValue)
   at AngleSharp.Dom.Collections.NamedNodeMap.SetNamedItemWithNamespaceUri(IAttr item)
   at AngleSharp.Dom.Element.SetOwnAttribute(String name, String value)
   at AngleSharp.Dom.Element.SetAttribute(String name, String value)
   at AngleSharp.Parser.Html.HtmlForeignExtensions.AdjustAttribute(Element element, String name, String value)
   at AngleSharp.Parser.Html.HtmlDomBuilder.CreateForeignElementFrom(HtmlTagToken tag)
   at AngleSharp.Parser.Html.HtmlDomBuilder.ForeignSpecialTag(HtmlTagToken tag)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Foreign(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Consume(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(HtmlParserOptions options)
   at AngleSharp.Parser.Html.HtmlParser.Parse(String source)

Example url: http://www.microsoftstore.com/store/msusa/en_US/home

**Comment by FlorianRappl** [comment]
Thanks for the report. I was able to identify the problem and fix the behavior. The fix will be published in the upcoming release (v0.9.3).
