### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#163]
at AngleSharp.Dom.Css.SimpleSelector.<>c__DisplayClass4.<.ctor>b__2(IElement _)
   at AngleSharp.Dom.Css.SimpleSelector.Match(IElement element)
   at AngleSharp.Dom.Css.CompoundSelector.Match(IElement element)
   at AngleSharp.Dom.Css.ListSelector.Match(IElement element)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, ISelector selector)
   at AngleSharp.Extensions.QueryExtensions.QuerySelector(INodeList elements, String selectors)
   at AngleSharp.Dom.Document.QuerySelector(String selectors)

**Comment by FlorianRappl** [comment]
Again. WIthout a MWE this can't be reproduced.
https://en.wikipedia.org/wiki/Minimal_Working_Example
