### ISSUE TITLE
Exception of type 'System.InvalidOperationException' was thrown

### ISSUE THREAD

**Issue by codeproject-solutions** [AngleSharp/AngleSharp#505]
at System.Runtime.CompilerServices.ConditionalWeakTable`2.VerifyIntegrity()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   at AngleSharp.Dom.Document..ctor(IBrowsingContext context, TextSource source)
   at AngleSharp.Parser.Html.HtmlParser.Parse(String source)

**Comment by FlorianRappl** [comment]
This report is useless as it does neither contain the version of AngleSharp you are using, nor the platform. Also a MWE is required to reproduce issues.

Could you please provide these? Otherwise, I need to close this one. Thanks 👍 !
