### ISSUE TITLE
String was not recognized as a valid DateTime when opening url

### ISSUE THREAD

**Issue by burlandm** [AngleSharp/AngleSharp#663]
I have some very simple code:

            var siteUrl = "https://richmond.csod.com/ats/careersite/search.aspx?site=1&c=richmond";

            var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
            var currentContext = BrowsingContext.New(configuration);
            var originalDoc = currentContext.OpenAsync(siteUrl).Result;

This works fine in version 0.9.9. It worked at first when I upgraded to 0.9.9.2, but when I did this:

            var t = Task.Delay(1000).ContinueWith(ts =>
            {
                configuration = Configuration.Default.WithDefaultLoader().WithCookies();
                currentContext = BrowsingContext.New(configuration);
                originalDoc = currentContext.OpenAsync(siteUrl).Result;

                Console.WriteLine(originalDoc.DocumentElement.OuterHtml);
            });

It starts throwing (on the OpenAsync line):

```
   String was not recognized as a valid DateTime.
   
      at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at AngleSharp.Services.Default.MemoryCookieProvider.Sanatize(String cookie)
   at AngleSharp.Services.Default.MemoryCookieProvider.SetCookie(String origin, String value)
   at AngleSharp.Dom.Document.set_Cookie(String value)
   at AngleSharp.Dom.Document.Setup(CreateDocumentOptions options)
   at AngleSharp.Dom.Html.HtmlDocument.<LoadAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.BrowsingContextExtensions.<OpenAsync>d__2.MoveNext()
```

And then it seems like even the original code without the task will run anymore. Switching back to 0.9.9 instantly solves the problem. I've had this happen with several completely unrelated Urls. 

Does anybody have any idea what might be going on here?

**Comment by FlorianRappl** [comment]
This definitely is a problem in the cookie provider.
