### ISSUE TITLE
Is there a way to prevent unobserved exceptions?

### ISSUE THREAD

**Issue by vonLeheCreative** [AngleSharp/AngleSharp#698]
Hi there. I'm using AngleSharp 0.9.10. The following page includes a css value that results in an integer overflow, and I'm trying to handle (and ignore) this. However, the exception is happening on one of AngleSharp's "fire and forget" background tasks, and thus doesn't get thrown until the Task's finalizer is called, which results in a call to TaskScheduler.UnobservedTaskException.

Unfortunately, the application I work on contains some generic code that detects such unobserved exceptions and displays them as errors to users. This generic code doesn't have any knowledge/dependency on AngleSharp, and I'd prefer not to hack it to ignore these particular exceptions.

Is there any way I can force these exceptions to be thrown in a way that I can catch/observe? I thought that perhaps I just needed to call IHtmlDocument.Dispose, but that didn't resolve the issue.

### Page:
https://brickset.com/sets/year-2018

### Exception:
```
Error Message:
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Stack Trace:
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at AngleSharp.Parser.Css.CssNumberToken.get_IntegerValue()
   at AngleSharp.Extensions.ValueExtensions.ToInteger(IEnumerable`1 value)
   at AngleSharp.Css.ValueConverters.StructValueConverter`1.Convert(IEnumerable`1 value)
   at AngleSharp.Css.ValueConverters.OrValueConverter.Convert(IEnumerable`1 value)
   at AngleSharp.Css.ValueConverters.OrValueConverter.Convert(IEnumerable`1 value)
   at AngleSharp.Css.ValueConverters.OrValueConverter.Convert(IEnumerable`1 value)
   at AngleSharp.Dom.Css.CssProperty.TrySetValue(CssValue newValue)
   at AngleSharp.Parser.Css.CssBuilder.CreateDeclarationWith(Func`2 createProperty, CssToken& token)
   at AngleSharp.Parser.Css.CssBuilder.FillDeclarations(CssStyleDeclaration style)
   at AngleSharp.Parser.Css.CssBuilder.CreateStyle(CssToken current)
   at AngleSharp.Parser.Css.CssBuilder.CreateRule(CssToken token)
   at AngleSharp.Parser.Css.CssBuilder.CreateRules(CssStyleSheet sheet)
   at AngleSharp.Parser.Css.CssParser.<ParseStylesheetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Dom.Css.CssStyleEngine.<ParseStylesheetAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Dom.Html.HtmlStyleElement.<CreateSheetAsync>d__21.MoveNext()
```

My code is pretty simple:
```
string html = ...;
HtmlParser parser = new HtmlParser();
using (IHtmlDocument document = parser.Parse(html))
{
    // Starting at document.Body, walk all element.Children and access element.TextContent.
    ...
}
```
Thanks,
Ehren

**Comment by FlorianRappl** [comment]
Hm, potentially there is a way (by supplying your own event loop, i.e., managing the tasks yourself), but I am not sure and it could be cumbersome. For me this screams for a more generic mechanism (i.e., like the error event).

I'll put it on the list for improvements.

**Comment by vonLeheCreative** [comment]
Great, thanks!

**Comment by EamonNerbonne** [comment]
I'm seeing something similar; a bunch of unobserved task exceptions, albeit with a different stacktrace:

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.) 
---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute. 
 at System.Collections.Generic.List`1.Enumerator.MoveNextRare() 
 at AngleSharp.Dom.Document.get_Body()
 at AngleSharp.Dom.Document.RaiseLoadedEvent()
 at AngleSharp.Browser.EventLoopExtensions.<>c__DisplayClass0_0.<Enqueue>b__0(CancellationToken c) 
 at AngleSharp.Browser.TaskEventLoop.TaskEventLoopEntry.<>c__DisplayClass8_0.<Run>b__0()
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) 
--- End of stack trace from previous location where exception was thrown ---
 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) 
--- End of inner exception stack trace --- 
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
 at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
 at AngleSharp.Dom.Document.get_Body()
 at AngleSharp.Dom.Document.RaiseLoadedEvent()
 at AngleSharp.Browser.EventLoopExtensions.<>c__DisplayClass0_0.<Enqueue>b__0(CancellationToken c)
 at AngleSharp.Browser.TaskEventLoop.TaskEventLoopEntry.<>c__DisplayClass8_0.<Run>b__0()
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) 
--- End of stack trace from previous location where exception was thrown ---
 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<--- 
```

I have no indications this is causing knock-on failures, even though concurrent modification of a (potentially unsynchronized?) List<> on a background thread sounds tricky.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
