### ISSUE TITLE
HtmlDocument.ParseDocumentAsync results in ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by KoalaBear84** [AngleSharp/AngleSharp#893]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?
Yes, #452 But was nothing wrong.

For more information, see the `CONTRIBUTING` guide.

## Description

Exception when parsing a 'document'.

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index must be within the bounds of the List. (Parameter 'index')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at AngleSharp.Html.Parser.HtmlDomBuilder.HeisenbergAlgorithm(HtmlTagToken tag)
   at AngleSharp.Html.Parser.HtmlDomBuilder.InBodyEndTag(HtmlTagToken tag)
   at AngleSharp.Html.Parser.HtmlDomBuilder.InCell(HtmlToken token)
   at AngleSharp.Html.Parser.HtmlDomBuilder.<ParseAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AngleSharp.Html.Parser.HtmlParser.<ParseAsync>d__28.MoveNext()
```

## Steps to Reproduce

```csharp
await new HtmlParser().ParseDocumentAsync(await new HttpClient().GetStringAsync("http://www.artfiles.org/netlib.org/blast/blast-nearterm"));
```

**Expected behavior:**

That it handles the input without exception.

**Actual behavior:**

Something internally goes wrong.

**Environment details:**

.NET Core 3.1 on Windows 10 Pro 2004

## Possible Solution

It looks like it must be something with list management. Hopefully it's clear and quick to fix.

**Comment by FlorianRappl** [comment]
Yeah unfortunately the given thing is no HTML.

Have you checked out http://www.artfiles.org/netlib.org/blast/blast-nearterm ?

While this is indeed a bug (thanks for creating the issue!) I think you don't want to parse the given source as HTML.

**Comment by KoalaBear84** [comment]
Haha, yes, it's a load of MIME, sorry, forgot to mention.

And indeed, they only reason for creating the issue was that it should not 'crash'. It's an unintentional parse (a result of the 'directory' above it). Np and thanks.

**Comment by FlorianRappl** [comment]
> And indeed, they only reason for creating the issue was that it should not 'crash'

Indeed - apparently it hits one of the rare edge cases (heisenberg algorithm ;D) - which is tested, but obviously not under the given conditions. So its a great case!

Thanks for issuing! Fix incoming!

**Comment by FlorianRappl** [comment]
Fix available in the preview and in `devel`.

**Comment by KoalaBear84** [comment]
Thanks, 'verified'! 👍
