### ISSUE TITLE
Parsing fails on some sites with "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by mitja-p** [AngleSharp/AngleSharp#94]
Site on which it fails: http://www.rtvslo.si/
This used to work before.

I am loading site with:
    public static IConfiguration defConfig = new Configuration(null, null, null).WithCss();

```
public static async Task<IDocument> LoadHtml(byte[] html, string url)
{
  var bcontext = BrowsingContext.New(defConfig);
  var ms = new MemoryStream(html);
  var doc = await bcontext.OpenAsync(m => m.Content(ms).Address(url));
  return doc;
```

   }

Exception raised is:
Data: System.Collections.ListDictionaryInternal
Message: Object reference not set to an instance of an object.
Stack:
   at AngleSharp.Dom.Html.HtmlLinkElement.TargetChanged()
   at AngleSharp.Dom.Html.HtmlLinkElement.<.ctor>b__1(String value)
   at AngleSharp.Dom.Element.AttributeChanged(String localName, String namespaceUri, String oldValue, Boolean suppressMutationObservers)
   at AngleSharp.Parser.Html.HtmlParserExtensions.SetAttributes(Element element, List`1 attributes)
   at AngleSharp.Parser.Html.HtmlParser.SetupElement(Element element, HtmlTagToken tag, Boolean acknowledgeSelfClosing)
   at AngleSharp.Parser.Html.HtmlParser.AddElement(HtmlTagToken tag, Boolean acknowledgeSelfClosing)
   at AngleSharp.Parser.Html.HtmlParser.InHead(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlParser.Home(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlParser.Consume(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlParser.<KernelAsync>d__6.MoveNext()

**Comment by FlorianRappl** [comment]
Thanks for the report! I'll look into it.

**Comment by FlorianRappl** [comment]
Is fixed in upcoming release.
